### ISSUE TITLE
很好奇为什么第一章中举的搜索例子有植物神经紊乱？

### ISSUE THREAD

**Issue by rubyyc** [sg552/happy_book_developer_career#1]
很好奇为什么第一章中举的搜索的三个例子钟有一个是植物神经紊乱？练气功？大佬在练气功吗？

**Comment by sg552** [comment]
是的。不好意思才看到留言。
之前熬夜太过分，差点挂了。
所以通过自我求医和学习慢慢好过来。 
现在可以在siwei.me上看到我的各种经验。
